'use strict';
(() => {
 const el=id=>document.getElementById(id);
 const REPO='Whoops-Lambo/austinwestphalmusic', BRANCH='main', DRAFT='awm-content-draft-v1';
 const kinds=['songs','lyrics','chordCharts','events'];
 const definitions={songs:[['title','Song title'],['description','Description','textarea'],['audioFile','Audio file URL'],['listenUrl','Streaming link']],lyrics:[['title','Song title'],['artist','Artist'],['description','Description','textarea'],['fileUrl','PDF URL'],['text','Lyrics text','textarea']],chordCharts:[['title','Song title'],['artist','Artist'],['key','Musical key'],['description','Description','textarea'],['fileUrl','PDF URL'],['text','Chord chart text','textarea']],events:[['title','Event title'],['date','Date / time'],['location','Location'],['ticketUrl','Event details link']]};
 let token='', config=null, baseSha=null, pending=new Map(), dirty=false, busy=false;
 const disabledBefore=new WeakMap();
 function status(message,error=false){el('admin-status').textContent=message;el('admin-status').dataset.error=String(error);}
 function changed(){dirty=true;}
 function lock(value){busy=value;el('editor').querySelectorAll('button,input,textarea').forEach(n=>{if(value){disabledBefore.set(n,n.disabled);n.disabled=true;}else if(disabledBefore.has(n)){n.disabled=disabledBefore.get(n);disabledBefore.delete(n);}});el('publish').disabled=value||!token;}
 async function api(path,method='GET',body){
  const controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),45000);
  try{const response=await fetch('https://api.github.com/repos/'+REPO+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal,cache:'no-store',redirect:'error'});
   if(!response.ok){const messages={401:'GitHub did not accept this token. Reconnect with a valid, unexpired token.',403:'GitHub denied this action. Check token expiration, repository access, Contents: Read and write, and branch rules. A rate limit may also apply.',404:'GitHub could not find the repository or content. Check that the token has access to austinwestphalmusic.',409:'The repository changed. Reconnect to load the latest content before publishing.',422:'GitHub could not apply this update. The branch may have changed or require a pull request. Reconnect before retrying.'};throw Error(messages[response.status]||'GitHub request failed ('+response.status+'). Your edits remain in the editor.');}
   return await response.json();
  }catch(e){if(e.name==='AbortError')throw Error('GitHub took too long to respond. Check the repository before retrying; a publish may have completed.');throw e;}finally{clearTimeout(timeout);}
 }
 function decodeBase64(content){return new TextDecoder().decode(Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0)));}
 function normalize(c){if(!c||typeof c!=='object'||Array.isArray(c))throw Error('The site content is not a valid configuration.');const result=structuredClone(c);for(const k of kinds){if(result[k]!==undefined&&!Array.isArray(result[k]))throw Error('Invalid '+k+' collection.');result[k]=(result[k]||[]).map(item=>{if(!item||typeof item!=='object'||Array.isArray(item))throw Error('Invalid entry in '+k+'.');return item;});}return result;}
 function field(label,value,type='text',onChange){const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;else wrapper.className='field-wide';input.value=typeof value==='string'?value:'';input.addEventListener('input',()=>{onChange(input.value);changed();});wrapper.append(input);return wrapper;}
 function drawGeneral(){const grid=el('general-fields');grid.replaceChildren();for(const [key,label,type] of [['heroTitle','Homepage heading (new line for second line)','textarea'],['heroDescription','Homepage introduction','textarea'],['aboutTitle','Story heading','textarea'],['aboutText','Story introduction','textarea'],['aboutSecondParagraph','Story second paragraph','textarea'],['email','Booking email','email']])grid.append(field(label,config[key],type||'text',v=>config[key]=v));for(const [key,names] of [['streamingLinks',['Spotify','Apple Music','YouTube']],['socialLinks',['Instagram','Facebook','TikTok']]]){config[key]??={};for(const name of names)grid.append(field(name+' URL',config[key][name],'url',v=>config[key][name]=v));}}
 function cleanupUploads(){const used=new Set(kinds.flatMap(k=>config[k].flatMap(x=>[x.fileUrl,x.audioFile])));for(const path of pending.keys())if(!used.has(path))pending.delete(path);}
 async function selectUpload(file,item,key,output){
  if(!file||busy)return;lock(true);try{
   const audio=key==='audioFile', limit=audio?20:5;
   if(file.size>limit*1024*1024)throw Error('This file is larger than '+limit+' MB.');
   if(file.size===0)throw Error('This file is empty.');
   const extension=file.name.split('.').pop().toLowerCase();
   if(audio?!['mp3','m4a','wav','ogg'].includes(extension):extension!=='pdf')throw Error(audio?'Choose an MP3, M4A, WAV, or OGG audio file.':'Choose a PDF document.');
   if(!audio&&new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-')throw Error('This file does not appear to be a valid PDF.');
   if([...pending.values()].reduce((n,f)=>n+f.size,0)+file.size>30*1024*1024)throw Error('Publish your pending uploads before adding more (30 MB per publish).');
   const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));
   const stem=file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,65)||'resource';
   const path='uploads/'+(audio?'audio':'documents')+'/'+crypto.randomUUID()+'-'+stem+'.'+extension;
   pending.set(path,{content:btoa(binary),size:file.size});item[key]=path;cleanupUploads();changed();drawCollections();status(file.name+' added to this draft. Publish changes to make it available.');
  }catch(e){output.textContent=e.message;status(e.message,true);}finally{lock(false);}
 }
 function drawCollections(){for(const kind of kinds){const box=el('edit-'+kind);box.replaceChildren();if(!config[kind].length){const p=document.createElement('p');p.textContent='Nothing added yet. Use the Add button to create your first entry.';box.append(p);}config[kind].forEach((item,index)=>{const card=document.createElement('article');card.className='edit-item';const heading=document.createElement('div');heading.className='edit-item-heading';const title=document.createElement('h3');title.textContent=(kind==='songs'?'Song':kind==='events'?'Event':kind==='lyrics'?'Document':'Chart')+' '+(index+1);const actions=document.createElement('div');for(const [label,offset] of [['Move up',-1],['Move down',1]]){const b=document.createElement('button');b.type='button';b.className='text-button';b.textContent=label;b.style.marginRight='14px';b.disabled=index+offset<0||index+offset>=config[kind].length;b.addEventListener('click',()=>{[config[kind][index],config[kind][index+offset]]=[config[kind][index+offset],config[kind][index]];changed();drawCollections();});actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.className='text-button remove-item';remove.textContent='Remove';remove.addEventListener('click',()=>{config[kind].splice(index,1);cleanupUploads();changed();drawCollections();});actions.append(remove);heading.append(title,actions);card.append(heading);const grid=document.createElement('div');grid.className='field-grid';for(const [key,label,type] of definitions[kind])grid.append(field(label,item[key],type||'text',v=>{item[key]=v;cleanupUploads();}));card.append(grid);
 if(kind!=='events'){const audio=kind==='songs', key=audio?'audioFile':'fileUrl';const label=document.createElement('label');label.className='upload-label';label.textContent=audio?'Or upload audio (MP3, M4A, WAV, OGG · max 20 MB)':'Or upload a PDF (max 5 MB)';const input=document.createElement('input');input.type='file';input.accept=audio?'.mp3,.m4a,.wav,.ogg':'.pdf,application/pdf';const state=document.createElement('p');state.className='upload-state';state.textContent=pending.has(item[key])?'Upload ready to publish.':'';input.addEventListener('change',()=>selectUpload(input.files[0],item,key,state));label.append(input);card.append(label,state);}
 box.append(card);});}}
 function showEditor(){el('connect-panel').hidden=true;el('editor').hidden=false;el('connection-state').textContent=token?'Connected · '+REPO:'Preview mode · connect to publish';el('disconnect').textContent=token?'Disconnect':'Back to connection';drawGeneral();drawCollections();lock(false);}
 function switchTab(key){for(const button of document.querySelectorAll('[data-tab]')){const selected=button.dataset.tab===key;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;el('panel-'+button.dataset.tab).hidden=!selected;}}
 el('connect-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;token=el('github-token').value.trim();el('github-token').value='';const button=event.submitter;button.disabled=true;busy=true;status('Connecting and loading your latest repository content…');try{const ref=await api('/git/ref/heads/'+BRANCH);const contents=await api('/contents/site-config.json?ref='+ref.object.sha);config=normalize(JSON.parse(decodeBase64(contents.content)));baseSha=ref.object.sha;pending.clear();dirty=false;showEditor();status('Connected. Edit your content, then publish when you’re ready.');}catch(e){token='';status(e.message||'Connection failed. Check your network and token.',true);}finally{button.disabled=false;busy=false;}});
 el('preview-editor').addEventListener('click',async()=>{if(busy)return;busy=true;el('preview-editor').disabled=true;try{const response=await fetch('site-config.json',{cache:'no-store'});if(!response.ok)throw Error('Could not load site content.');config=normalize(await response.json());baseSha=null;pending.clear();dirty=false;token='';showEditor();status('Preview mode: explore the editor and save a local draft. Connect to GitHub to publish.');}catch(e){status(e.message,true);}finally{busy=false;el('preview-editor').disabled=false;}});
 el('disconnect').addEventListener('click',()=>{if(dirty&&!confirm('Disconnect and discard unsaved edits? Save a draft first if you want to keep them.'))return;token='';config=null;pending.clear();baseSha=null;dirty=false;el('content-form').reset();el('editor').hidden=true;el('connect-panel').hidden=false;el('github-token').value='';status('Disconnected. The token has been cleared.');});
 document.querySelectorAll('[data-tab]').forEach(button=>{button.addEventListener('click',()=>switchTab(button.dataset.tab));button.addEventListener('keydown',event=>{const buttons=[...document.querySelectorAll('[data-tab]')];let index=buttons.indexOf(button);if(event.key==='ArrowRight')index=(index+1)%buttons.length;else if(event.key==='ArrowLeft')index=(index+buttons.length-1)%buttons.length;else if(event.key==='Home')index=0;else if(event.key==='End')index=buttons.length-1;else return;event.preventDefault();switchTab(buttons[index].dataset.tab);buttons[index].focus();});});
 document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>{const kind=button.dataset.add;config[kind].push({title:''});changed();drawCollections();el('edit-'+kind).lastElementChild.querySelector('input').focus();}));
 el('content-form').addEventListener('submit',e=>e.preventDefault());
 el('save-draft').addEventListener('click',()=>{try{localStorage.setItem(DRAFT,JSON.stringify({config,pending:[...pending],baseSha,savedAt:new Date().toISOString()}));dirty=false;status('Draft saved on this browser. The live website has not changed.');}catch{status('This browser could not save the draft (storage may be full). Publish your uploads or keep this tab open.',true);}});
 el('restore-draft').addEventListener('click',()=>{try{const raw=localStorage.getItem(DRAFT);if(!raw)throw Error('No saved draft found on this browser.');const draft=JSON.parse(raw);if(token&&draft.baseSha&&draft.baseSha!==baseSha)throw Error('This draft was saved against an older repository version. Review the latest content before re-entering your changes.');if(dirty&&!confirm('Replace current edits with your saved draft?'))return;config=normalize(draft.config);pending=new Map(draft.pending||[]);for(const [path,file] of pending){if(!/^uploads\/(audio|documents)\/[a-zA-Z0-9_.-]+$/.test(path)||typeof file.content!=='string'||! /^[A-Za-z0-9+/=]*$/.test(file.content)||file.content.length>30*1024*1024)throw Error('Invalid upload in saved draft.');}cleanupUploads();changed();drawGeneral();drawCollections();status('Draft restored. Review your changes before publishing.');}catch(e){status(e.message||'Could not restore this draft.',true);}});
 function validURL(value,local=false){if(!value)return true;if(typeof value!=='string')return false;try{const url=new URL(value,location.href);return url.protocol==='https:'||(local&&url.origin===location.origin&&url.protocol===location.protocol);}catch{return false;}}
 function validate(){if(JSON.stringify(config).length>500000)throw Error('Text content is too large. Upload a PDF instead of pasting very large documents.');if(!el('content-form').checkValidity()){switchTab('general');el('content-form').reportValidity();throw Error('Please correct the highlighted field.');}for(const [key,value] of Object.entries(config.streamingLinks||{}))if(!validURL(value))throw Error(key+' needs an HTTPS URL.');for(const [key,value] of Object.entries(config.socialLinks||{}))if(!validURL(value))throw Error(key+' needs an HTTPS URL.');if(config.email&&!/^[^\s@?&#]+@[^\s@?&#]+\.[^\s@?&#]+$/.test(config.email))throw Error('Enter a valid booking email.');for(const kind of kinds)for(const [i,item] of config[kind].entries()){const name=kind+' entry '+(i+1);if(!item.title?.trim())throw Error('Add a title to '+name+'.');for(const key of ['fileUrl','audioFile','listenUrl','ticketUrl'])if(!validURL(item[key],key==='fileUrl'||key==='audioFile'))throw Error('Add a valid HTTPS or local file URL to '+name+'.');if((kind==='lyrics'||kind==='chordCharts')&&!item.text?.trim()&&!item.fileUrl?.trim())throw Error('Add a PDF or text to '+name+'.');if(kind==='songs'&&!item.audioFile?.trim()&&!item.listenUrl?.trim())throw Error('Add audio or a streaming link to '+name+'.');}}
 el('publish').addEventListener('click',async()=>{if(busy||!token)return;try{validate();}catch(e){status(e.message,true);return;}cleanupUploads();lock(true);status('Checking the repository before publishing…');try{
  const ref=await api('/git/ref/heads/'+BRANCH);if(ref.object.sha!==baseSha)throw Error('The repository changed since you connected. Save a draft, disconnect, and reconnect to review the latest content. No changes were published.');
  const parent=await api('/git/commits/'+baseSha), tree=[];let number=0;
  for(const [path,file] of pending){status('Uploading file '+(++number)+' of '+pending.size+'…');const blob=await api('/git/blobs','POST',{content:file.content,encoding:'base64'});tree.push({path,mode:'100644',type:'blob',sha:blob.sha});}
  tree.push({path:'site-config.json',mode:'100644',type:'blob',content:JSON.stringify(config,null,2)+'\n'});
  status('Saving your content in GitHub…');const newTree=await api('/git/trees','POST',{base_tree:parent.tree.sha,tree});const commit=await api('/git/commits','POST',{message:'Update artist content from admin panel',tree:newTree.sha,parents:[baseSha]});await api('/git/refs/heads/'+BRANCH,'PATCH',{sha:commit.sha,force:false});baseSha=commit.sha;pending.clear();dirty=false;try{localStorage.removeItem(DRAFT);}catch{}drawCollections();status('Published to GitHub. The live site will update when GitHub Pages finishes deploying. Commit '+commit.sha.slice(0,7)+'.');
 }catch(e){status(e.message||'Publishing failed. Check your network. Your edits remain in the editor.',true);}finally{lock(false);}});
 window.addEventListener('beforeunload',event=>{if(dirty||busy){event.preventDefault();event.returnValue='';}});
})();
